config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/projects'
  get 'pages/web_development'
  get 'pages/contact'
  get 'pages/index'

  resources :blogs, only: [:create, :new, :show, :destroy, :index, :update]
#For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end

  def web_development
  end

  def contact
  end

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarikenWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/03973d01eb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <ul>
        <div class="tabs">
          <div id="home-tab"><li><%= link_to "HOME", pages_home_path %></li></div>
          <div><li><%= link_to "About me", pages_about_path %></li></div>
          <div><li><%= link_to "Projects", pages_projects_path %></li></div>
          <div><li><%= link_to "Web development", pages_web_development_path %></li></div>
          <div><li><%= link_to "Contact", pages_contact_path %></li></div>
        </div>
      </ul>
    </div>
    <%= yield %>

    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="img-grid">
    <div class="img-a"></div>
    <div class="img-b"></div>
    <div class="img-c"></div>
    <div class="img-d"></div>
    <div class="img-e"></div>
    <div class="img-f"></div>
  </div>
  <div class="content">
    <h1>About me</h1>
    <p>Hi, I am <b>Mariken</b>, passionate about nature, documentary films, food and solving puzzles from sudoku’s to complex strategic problems.</p>
    <p>I have 4+ years experience in designing (digital) products  and services, helping companies expand their markets and creating deep connections with their customers. Working in business development and strategy drives me to always be aware of customer pain points and developing strategies to help meet customer needs.</p>
    <p>I am also an advocate for raising awareness around mental support for people with an autoimmune disease and currently working on a documentary film about young women and sexuality.</p>
    <p>Checkout some of products and services I developed for different companies.</p>
    <div id="btn-green-about">
      <%= link_to "View projects", pages_projects_path, class: "btn-green"%>
    </div>
  </div>
</div>
<div class="contact-container-content">
  <div class="contact-title">
    <h1>Need help with designing and developing a new product or service?</h1>
    <h2>Send me a message and let’s discuss how I can help you.</h2>
  </div>
  <div class="contact-button">
    <%= link_to "Send me a message", pages_contact_path, class: "btn-green-message"%>
  </div>
</div>

app/views/pages/contact.erb
<div class="contact-page">
  <h1>Like what you see? Let’s work together! </h1>
  <h2>I can help you with the following topics:</h2>
  <div class="contact-content">
    <ul>
      <li>Market research</li>
      <li>Market entry strategy</li>
      <li>Creative concepts</li>
      <li>Project management</li>
      <li>Website design</li>
      <li>User interface and experience design</li>
      <li>User research</li>
      <li>eCommerce</li>
    </ul>
  </div>
  <div class="contact-me">
    <h2>Send me an <a href="mailto:mvangulpen@gmail.com"><i class="fas fa-envelope-square"></i></a> <br> ... or contact me via <a href="https://www.linkedin.com/in/mariken-van-gulpen-18942243/" target="_blank"><i class="fab fa-linkedin-in"></i></a></h2>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-name">
    <h1>Mariken van Gulpen</h1>
  </div>
  <div class="banner-title">
    <div class="banner-content">
      <h1> Strategy & <br> Business Development Manager </h1>
      <%= link_to "Find out more about me", pages_about_path, class: "btn-burgundy"%>
    </div>
  </div>
</div>
<div class="home-container">
  <div>
    <h1>Innovative product and service development</h1>
  </div>
  <div class="card-container">
    <div class="card-product">
      <div class="card-img-scooter">a</div>
      <div class="card-content">
        <h3>Adjusting products and services to local markets.</h3>
      </div>
      <div class="card-button">
        <%= link_to "View project", pages_projects_path, class: "btn-green"%>
      </div>
    </div>
    <div class="card-product">
      <div class="card-img-travel"></div>
      <div class="card-content">
        <h3>Developing innovative products & services solving customer pain points.</h3>
      </div>
      <div class="card-button">
        <%= link_to "View project", pages_projects_path, class: "btn-green"%>
      </div>
    </div>
    <div class="card-product">
      <div class="card-img-mobile"></div>
      <div class="card-content">
        <h3>Simplifying online processes & developing intuitive apps and websites.</h3>
      </div>
      <div class="card-button">
        <%= link_to "View project", pages_projects_path, class: "btn-green"%>
      </div>
    </div>
  </div>
</div>
<div class="home-container-2">
  <div>
    <h1>Web development projects</h1>
  </div>
  <div class="card-container">
    <div class="card-product">
      <div class="img-helpal">
        <a style="display: none" href="https://www.freepik.com/free-photos-vectors/people">People vector created by pikisuperstar - www.freepik.com</a>
      </div>
      <div class="card-content">
        <h3>Helpal</h3>
        <p>Helps you find support for all the problems you face moving to a new city or even new country. Get help  from the local community fast and easy.</p>
      </div>
      <div class="card-button">
        <%= link_to "View project", pages_web_development_path, class: "btn-green"%>
      </div>
    </div>
    <div class="card-product">
      <div class="img-hackathon"></div>
      <div class="card-content">
        <h3>WirvsVirus Hackathon</h3>
        <p>Home Alone Challenge, an app to beat loneliness in times of COVID-19. Receive a challenge each day, get support and share your results. </p>
      </div>
      <div class="card-button">
        <%= link_to "View project", pages_web_development_path, class: "btn-green"%>
      </div>
    </div>
    <div class="card-product">
      <div class="img-car">
        <a style="display: none" href='https://www.freepik.com/photos/car'>Car photo created by azerbaijan_stockers - www.freepik.com</a>
      </div>
      <div class="card-content">
        <h3>CarsBnB</h3>
        <p>Rent a car or share your car with people in your city. Fast, convenient and easy.</p>
      </div>
    </div>
  </div>
</div>
<div class="contact-container">
  <h1>Let’s work together</h1>
  <h2>I can help you with:</h2>
  <div class="contact-content">
    <ul>
      <li>Market research</li>
      <li>Market entry strategy</li>
      <li>Creative concepts</li>
      <li>Project management</li>
      <li>Website design</li>
      <li>User interface and experience design</li>
      <li>User research</li>
      <li>eCommerce</li>
    </ul>
  </div>
  <div class="contact-me">
    <div>
      <h2>Let’s discuss how I can help you.</h2>
    </div>
    <div class="contact-me-button">
      <a class="btn-green-message", href="mailto:mvangulpen@gmail.com">Send me message</a>
    </div>
  </div>
</div>

app/views/pages/index.erb
<div class="index-block">Hello</div>

app/views/pages/projects.erb
<div class="project-container">
  <h1>Introducing new speed limit e-scooter</h1>
  <div class="project-description">
    <div class="img-scooter"></div>
    <div class="project-content">
      <div class="project-table">
        <table>
          <tbody>
            <tr>
              <td><strong>Industry</strong></td>
              <td>automotive, e-mobility</td>
            </tr>
            <tr>
              <td><strong>Challenge</strong></td>
              <td>adapt product to local market</td>
            </tr>
            <tr>
              <td><strong>Role</strong></td>
              <td>project lead, research, operations, branding</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="case-summary">
        <h2>Description</h2>
        <p>Going live in a new country with your product is exciting. Copying your entry strategy from one country to the other should always be carefully considered.
        For one of the new markets where we introduced the e-scooter it soon became clear that customers expected more options. Especially when it came down to choosing the speed limit of their vehicle. Analyzing market data, customer feedback and performing surveys and interviews we realized to have a bigger impact we needed to introduce the extra option: the 25km/h e-scooter was introduced.
        It had a positive impact on reaching new customers and partners and increased sales numbers within the first weeks after launching the new product. </p>
      </div>
    </div>
  </div>
</div>
<div id="border"></div>
<div class="project-container travel-insurance">
  <h1>Flexible and modular travel insurance</h1>
  <div class="project-description">
    <div class="img-travel-hidden"></div>
    <div class="project-content">
      <div class="project-table">
         <table>
          <tbody>
            <tr>
              <td><strong>Industry</strong></td>
              <td>insurance, digital</td>
            </tr>
            <tr>
              <td><strong>Challenge</strong></td>
              <td>create flexible insurance modules adaptable to personal needs</td>
            </tr>
            <tr>
              <td><strong>Role</strong></td>
              <td>facilitation, research, prototype</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="case-summary">
        <h2>Description</h2>
        <p>What do people expect to be covered by their insurance and maybe more importantly, what do they not want to pay extra for?
        That was one of the main questions we wanted to get answered. Customers do not want the traditional insurance anymore where the insurance company dictates what you get covered. They want to be in control.
        Through performing extensive market research with more than 1000 EU respondents we discovered that the most important module for travel insurance is the benefit of receiving medical <strong>assistance</strong>.
        A travel insurance was created where people could pay per day, cancel per day and sign up anytime to receive medical assistance. The customer is in control and decides.</p>
      </div>
    </div>
    <div class="img-travel"></div>
  </div>
</div>
<div id="border"></div>
<div class="project-container mobile-banking">
  <h1>Intuitive and simple online sign-up process</h1>
  <div class="project-description">
    <div class="img-mobile"></div>
    <div class="project-content">
      <div class="project-table">
        <table>
          <tbody>
            <tr>
              <td><strong>Industry</strong></td>
              <td>insurance, mobile banking</td>
            </tr>
            <tr>
              <td><strong>Challenge</strong></td>
              <td>simplify insurance online registration process</td>
            </tr>
            <tr>
              <td><strong>Role</strong></td>
              <td>project lead, research, prototype</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="case-summary">
        <h2>Description</h2>
        <p>The mobile banking sector has been growing extensively over the past years creating opportunities for people to bring together all their finances into one place. Together with renowned mobile banking companies we designed flexbible insurances the customer could sign up for (and cancel) in three simple steps. This was made possible by developing a secure API connection with our partners.
        The customer clicks on the insurance option, sees the terms and conditions and signs up. The customer is less likely to step out during the registration process because of the many details they would normally have to fill out and added benefit is that the customer has an overview of all his finances in one app.</p>
      </div>
    </div>
  </div>
</div>
<div class="contact-container-content">
  <div class="contact-title">
    <h1>Need help with designing and developing a new product or service?</h1>
    <h2>Send me a message and let’s discuss how I can help you.</h2>
  </div>
  <div class="contact-button">
    <%= link_to "Send me a message", pages_contact_path, class: "btn-green-message"%>
  </div>
</div>

app/views/pages/web_development.erb
<div class="project-container">
  <h1>Helpal - get help from your local community</h1>
  <div class="project-description">
      <div class="img-helpal-mockup">
      <%= image_tag('helpal_mockup.png', alt: 'laptop') %>
    </div>
    <div class="project-content">
      <div class="project-table">
        <table>
          <tbody>
            <tr>
              <td><strong>Project</strong></td>
              <td>Platform for expats to ask for help regarding several topics</td>
            </tr>
            <tr>
              <td><strong>Skills</strong></td>
              <td>Ruby on Rails, JavaScript ES6, CSS, HTML, Figma </td>
            </tr>
            <tr>
              <td><strong>More info:</strong></td>
              <td>Check the design in <a href="https://www.figma.com/file/HV9AqCXSb8M6LMfoSW1OIy/Untitled?node-id=0%3A1" class="figma-link" target="_blank">Figma</a></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="case-summary">
        <h2>Description</h2>
        <p>It can be challenging moving to a new city or even a new country. Helpal offers expats and locals a platform where they can connect and help each other with questions regarding housing, legal, registration etc. Post a help request and connect with a pal and get your questions answered.</p>
      </div>
    </div>
  </div>
</div>
<div id="border"></div>
<div class="project-container">
  <h1>Home Alone Challenge - WirVsVirus Hackathon 2020</h1>
  <div class="project-description">
    <div class="project-content">
      <div class="project-table">
         <table>
          <tbody>
            <tr>
              <td><strong>Project</strong></td>
              <td>App for mental support and activities during COVID-19</td>
            </tr>
            <tr>
              <td><strong>Skills</strong></td>
              <td>Ruby on Rails, JavaScript ES6, Figma</td>
            </tr>
            <tr>
              <td><strong>More info:</strong></td>
              <td>Check the design in <a href="https://www.figma.com/file/Vtqgn4ShZdmwcB9HCCTMmH/Helpal?node-id=0%3A1" class="figma-link" target="_blank">Figma</a></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="case-summary">
        <h2>Description</h2>
        <p>The Home Alone Challenge app gives endless possibilities to be creative and active in isolation and to get in contact with many people at the same time. You can master new challenges every day.</p>
      </div>
    </div>
    <div class="img-home-mockup">
      <%= image_tag('home_mockup.png', alt: 'phone') %>
    </div>
  </div>
</div>

<div class="contact-container-content">
  <div class="contact-title">
    <h1>Need  help with your website or app?</h1>
    <h2>Send me a message and let’s discuss how I can help you.</h2>
  </div>
  <div class="contact-button">
    <%= link_to "Send me a message", pages_contact_path, class: "btn-green-message"%>
  </div>
</div>